In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [9]:
file_path = r'C:\Users\hp\Desktop\telecom-network-anomalies\data\raw\ip_addresses_sample\agg_10_minutes\11.csv'
df = pd.read_csv(file_path)
df.head()

,id_time,n_flows,n_packets,n_bytes,n_dest_asn,n_dest_ports,n_dest_ip,tcp_udp_ratio_packets,tcp_udp_ratio_bytes,dir_ratio_packets,dir_ratio_bytes,avg_duration,avg_ttl
0,0,31049,76327,5806461,1866.0,19475.0,21327.0,0.0,0.0,0.49,0.49,7.12,64.02
1,1,32765,77374,5887159,1870.0,20386.0,22550.0,0.0,0.0,0.49,0.49,6.11,63.16
2,2,30469,71407,5432005,1848.0,19425.0,21712.0,0.0,0.0,0.50,0.49,5.49,62.55
3,3,29960,69281,5271808,1890.0,19161.0,21388.0,0.0,0.0,0.50,0.50,6.50,63.42
4,4,35818,79865,6082582,1955.0,22111.0,25013.0,0.0,0.0,0.49,0.49,6.00,63.33

In [13]:
time_df = pd.read_csv(r'C:\Users\hp\Desktop\telecom-network-anomalies\data\raw\times\times_10_minutes.csv')
df = df.merge(time_df, on='id_time', how='left')